services:
  - type: web
    name: youtube-downloader-worker
    runtime: docker
    plan: starter
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: MAX_FILE_MB
        value: 1900
      - key: APP_DEBUG
        value: "0"
